<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>top.continew.admin</groupId>
        <artifactId>continew-admin</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>continew-server</artifactId>
    <packaging>jar</packaging>

    <name>${project.artifactId}</name>
    <description>API 及打包部署模块</description>

    <dependencies>
        <!-- 系统管理模块 -->
        <dependency>
            <groupId>top.continew.admin</groupId>
            <artifactId>continew-system</artifactId>
        </dependency>

        <!-- 能力开放插件 -->
        <dependency>
            <groupId>top.continew.admin</groupId>
            <artifactId>continew-plugin-open</artifactId>
        </dependency>

        <!-- 租户插件 -->
        <dependency>
            <groupId>top.continew.admin</groupId>
            <artifactId>continew-plugin-tenant</artifactId>
        </dependency>

        <!-- 任务调度插件 -->
        <dependency>
            <groupId>top.continew.admin</groupId>
            <artifactId>continew-plugin-schedule</artifactId>
        </dependency>

        <!-- 代码生成器插件 -->
        <dependency>
            <groupId>top.continew.admin</groupId>
            <artifactId>continew-plugin-generator</artifactId>
        </dependency>

        <!-- ContiNew Starter 链路追踪模块 -->
        <dependency>
            <groupId>top.continew.starter</groupId>
            <artifactId>continew-starter-trace</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <!-- 设置构建的 jar 包名 -->
        <finalName>${project.parent.name}</finalName>
        <plugins>
            <!-- Spring Boot 可执行 JAR 打包插件（胖包模式） -->
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <!-- 不跳过 Spring Boot 重新打包，将所有依赖打入 JAR -->
                    <skip>false</skip>
                    <!-- 是否将系统作用域的依赖包含进去 -->
                    <includeSystemScope>true</includeSystemScope>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>